let products = [
  {
    id: 1,
    name: 'Tomato',
    category: 'Vegetable',
    quantity: 100,
    price: 150,
    unit: 'kg',
    farmer: 'Sample Farmer',
    location: 'Dambulla',
  },
  {
    id: 2,
    name: 'Rice',
    category: 'Grain',
    quantity: 500,
    price: 220,
    unit: 'kg',
    farmer: 'Nimal Bandara',
    location: 'Anuradhapura',
  },
  {
    id: 3,
    name: 'Tea',
    category: 'Beverage Crop',
    quantity: 50,
    price: 1200,
    unit: 'kg',
    farmer: 'Priyantha Wickramasinghe',
    location: 'Nuwara Eliya',
  },
  {
    id: 4,
    name: 'Coconut',
    category: 'Fruit',
    quantity: 300,
    price: 60,
    unit: 'nuts',
    farmer: 'Sunil Rathnayake',
    location: 'Kurunegala',
  },
  {
    id: 5,
    name: 'Chili',
    category: 'Vegetable',
    quantity: 80,
    price: 400,
    unit: 'kg',
    farmer: 'Chamari Gunasekara',
    location: 'Kandy',
  },
]

let requests = [
  {
    id: 1,
    productId: 1,
    buyer: 'Kumar Silva',
    qtyRequested: 20,
    total: 3000,
    status: 'pending',
  },
  {
    id: 2,
    productId: 2,
    buyer: 'Nadeesha Perera',
    qtyRequested: 100,
    total: 22000,
    status: 'accepted',
  },
  {
    id: 3,
    productId: 3,
    buyer: 'Ruwan Fernando',
    qtyRequested: 10,
    total: 12000,
    status: 'rejected',
  },
  {
    id: 4,
    productId: 5,
    buyer: 'Amali Jayawardena',
    qtyRequested: 15,
    total: 6000,
    status: 'pending',
  },
]

module.exports = { products, requests }
